# Generated by Django 2.2.7 on 2019-11-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
