# Generated by Django 2.2.7 on 2019-11-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_auto_20191121_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='total_hours',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
